- EngineLayer/Analysis/AnalysisResults.cs
- EngineLayer/Gptmd/GptmdResults.cs
Tabs allow easy for easy separation in Excel
> Consistent results delimeters for modifications

- GUI/MainWindow.xaml
- GUI/MainWindow.xaml.cs
To solve the #293 
Don't load duplicate files. Allow user to sort file lists. GUI Enhancement Low-Hanging Fruit.
#293 opened 3 days ago by trishorts.
> Avoid load duplicate files

- EngineLayer/ClassicSearch/ClassicSearchEngine.cs
- EngineLayer/ClassicSearch/PsmClassic.cs
- EngineLayer/Proteomics/PeptideWithPossibleModifications.cs
- EngineLayer/Proteomics/PeptideWithSetModifications.cs
- EngineLayer/PsmWithMultiplePossiblePeptides.cs
Now variable mods are prefered over localized mods, and substitutions/removals are further de-emphasized
>  Now variable mods are prefered over localized mods, and substitutions/removals are further de-emphasized

- EngineLayer/ProteinGroup.cs
- GUI/CalibrateTaskWindow.xaml
- GUI/GPTMDTaskWindow.xaml
- GUI/SearchTaskWindow.xaml
- Test/RobTest.cs
#253 #237 
Please let me know when you want to check the code. Thank you.
> PTM info output

- TaskLayer/EverythingRunner/EverythingRunnerEngine.cs
- Test/MyTaskTest.cs
New Test that checks contents of pruned database that can be generated from a search task
> Pruned Database Test

- CMD/CMD.csproj
- CMD/Program.cs
- CMD/packages.config
- EngineLayer/CrosslinkAnalysis/CrosslinkAnalysisEngine.cs
- EngineLayer/CrosslinkAnalysis/CrosslinkAnalysisResults.cs
- EngineLayer/CrosslinkSearch/BestPeptideScoreNotch.cs
- EngineLayer/CrosslinkSearch/CrosslinkSearchEngine.cs
- EngineLayer/CrosslinkSearch/CrosslinkSearchEngine2.cs
- EngineLayer/CrosslinkSearch/CrosslinkSearchResults.cs
- EngineLayer/CrosslinkSearch/MatchedIonInfo.cs
- EngineLayer/CrosslinkSearch/PsmCross.cs
- EngineLayer/CrosslinkerType.cs
- EngineLayer/EngineLayer.csproj
- EngineLayer/XLSearchResults.cs
- EngineLayer/packages.config
- GUI/GUI.csproj
- GUI/MainWindow.xaml
- GUI/MainWindow.xaml.cs
- GUI/XLSearchTaskWindow.xaml
- GUI/XLSearchTaskWindow.xaml.cs
- GUI/packages.config
- TaskLayer/MetaMorpheusTask.cs
- TaskLayer/TaskLayer.csproj
- TaskLayer/XLSearchTask/XLSearchTask.cs
- TaskLayer/packages.config
- Test/Test.csproj
- Test/packages.config
XL Search Task added. The task is totally independent of other tasks which could be easily maintained. The XL Search Task still need further optimization of FDR and XLScore calculation; further features like quantification and other validation functions will be considered.
> XLSearch Task added

- EngineLayer/Data/proteases.tsv
- EngineLayer/Proteomics/ProteinExtensions.cs
> Addition of two proteases for fusion peptide identifications

- EngineLayer/ModernSearch/ModernSearchEngine.cs
Hi Stefan! If you could take a careful look at the comp ions calculations, I would appreciate it. It took several revisions to pass the unit tests, so I'm concerned there might still be errors that I'm blind to. Anyway, I'm enthusiastic that I think it's sped up more with the use of minimum as a floor and maximum as a ceiling.
> YEAH MODERN SEARCH WOOHOO

- EngineLayer/ClassicSearch/ClassicSearchEngine.cs
- EngineLayer/CrosslinkSearch/CrosslinkSearchEngine2.cs
- EngineLayer/Localization/LocalizationEngine.cs
- EngineLayer/MetaMorpheusEngine.cs
- EngineLayer/ModernSearch/ModernSearchEngine.cs
- Test/AddCompIonsTest.cs
- Test/TestDataFile.cs
Changes to unit tests are due to changes in intensity calculation.
> Implemented complimentary tolerances for classic search

- EngineLayer/Indexing/PrecursorIndexingEngine.cs
- EngineLayer/ModernSearch/ModernSearchEngine.cs
- EngineLayer/NonSpecificEnzymeSearch/NonSpecificEnzymeSearchEngine.cs
- TaskLayer/MetaMorpheusTask.cs
- TaskLayer/SearchTask/SearchTask.cs
- Test/SearchEngineTests.cs
awecauhiaweucbosdicjoaweinoiax
> NonSpecific Speed Up

- MetaMorpheusSetup/Product.wxs
* Fixed tooltip for custom
* Add files via upload
Deselect fixed
* Add files via upload
* updated version
* auto-update commited
* autoupdater
Updated Autoupdate form and mainwinsow. Make sure to change the directory to auto update file "Update.txt" which is in current folder.
* wix installer updated
Setup3 added, wix installer demo
* added setup
* deleted debug files
* deleted all
* deleted all
* obj deleted cache
* obj cleared
* deleted package
* hmphm
* deleted
* ah
* remove
* remove wax
* Hmphjm
* sln
* Release?
* Update MetaMorpheus.sln
* Update MetaMorpheus.sln
* ff
* haha
* mkay
* OutputNoice
* haha
* aha
* uhum
* hmph
* Noice
* Fixes
* version check
* 205 with auto_update
* added features
* Auto_Update
* installer updated
* Aha
* Yah
* Uhum
* uhum
* Wooh
* revert
* minor
* uhum
* …
> INstaller fix

- MetaMorpheusSetup/Product.wxs
* Fixed tooltip for custom
* Add files via upload
Deselect fixed
* Add files via upload
* updated version
* auto-update commited
* autoupdater
Updated Autoupdate form and mainwinsow. Make sure to change the directory to auto update file "Update.txt" which is in current folder.
* wix installer updated
Setup3 added, wix installer demo
* added setup
* deleted debug files
* deleted all
* deleted all
* obj deleted cache
* obj cleared
* deleted package
* hmphm
* deleted
* ah
* remove
* remove wax
* Hmphjm
* sln
* Release?
* Update MetaMorpheus.sln
* Update MetaMorpheus.sln
* ff
* haha
* mkay
* OutputNoice
* haha
* aha
* uhum
* hmph
* Noice
* Fixes
* version check
* 205 with auto_update
* added features
* Auto_Update
* installer updated
* Aha
* Yah
* Uhum
* uhum
* Wooh
* revert
* minor
* uhum
* …
> Fix installer

- TaskLayer/CalibrationTask/CalibrationTask.cs
- TaskLayer/FileSpecificSettings.cs
- TaskLayer/MetaMorpheusTask.cs
* OKay
* WriteIntermediateFiles fix
* params calibration bugfix
* Huge CommonParameters reorganization
* Uhum
* Looll
* Comment out final
* TextboxClear
* Calib fixes
* File specific precursor params
* yah
* Update CalibrationTask.cs
* Update FileSpecificSettings.cs
> Calib fix, toml write (#784)

- MetaMorpheusSetup/Product.wxs
* agh
* noice
* Fix protein group output
* fix
* fix
> Fix installer (#838)

- TaskLayer/GPTMDTask/GPTMDTask.cs
> Fix gptmd crash

- README.md
> Test release! (#937)

- EngineLayer/ModernSearch/ModernSearchEngine.cs
- Test/SearchEngineTests.cs
prevent index out of bounds errors in modern search
> modern search crash fix

- GUI/MainWindow.xaml.cs
fixed crash when dragged database in, checking it as contaminant, then adding a raw file
> fixed crash in GUI with contaminant database adding

- GUI/SearchTaskWindow.xaml
- GUI/SearchTaskWindow.xaml.cs
- TaskLayer/SearchTask/MyFileManager.cs
- disable ms/ms peak filtering because of major bug in mzlib
> disable ms/ms peak filtering because of major bug in mzlib

- EngineLayer/ProteinParsimony/ProteinGroup.cs
- EngineLayer/ProteinScoringAndFdr/ProteinScoringAndFdrEngine.cs
- GUI/MainWindow.xaml.cs
- TaskLayer/GPTMDTask/GPTMDTask.cs
fix top-picked protein FDR. removed output of summed protein group score (only used internally now)
> fix top-picked protein FDR

- EngineLayer/Proteomics/ProteinExtensions.cs
Added a check to ensure neither scissile bonds is null, in consistency with other proteases that handle this event.
> Semi digest fix2

- EngineLayer/Mods/RareMods.txt
> these are real but shouldn't be generally included

- EngineLayer/Indexing/IndexingEngine.cs
> Index out of bounds indexing engine fix

- CMD/CMD.csproj
- EngineLayer/EngineLayer.csproj
- GUI/GUI.csproj
- GUI/packages.config
- TaskLayer/CalibrationTask/CalibrationTask.cs
- TaskLayer/GPTMDTask/GPTMDTask.cs
- TaskLayer/MetaMorpheusTask.cs
- TaskLayer/MyFileManager.cs
- TaskLayer/NeoSearchTask/NeoSearchTask.cs
- TaskLayer/SearchTask/PostSearchAnalysisTask.cs
- TaskLayer/SearchTask/SearchTask.cs
- TaskLayer/TaskLayer.csproj
- TaskLayer/XLSearchTask/XLSearchTask.cs
- Test/ProteinLoaderTest.cs
- Test/Test.csproj
> MetaMorpheus Add for maxThreads in MzLib change

- EngineLayer/Mods/Mods.txt
> remove some mods

- GUI/GUI.csproj
- GUI/GUIsettings.toml
- GUI/MainWindow.xaml
- GUI/MainWindow.xaml.cs
- GUI/Util/GuiGlobalParams.cs
- MetaMorpheusSetup/Product.wxs
- Test/SlicedTest.cs
> Add youtube and wiki link

- EngineLayer/Indexing/IndexingEngine.cs
- TaskLayer/MetaMorpheusTask.cs
- TaskLayer/SearchTask/SearchTask.cs
- TaskLayer/XLSearchTask/XLSearchTask.cs
- Test/AddCompIonsTest.cs
- Test/FdrTest.cs
- Test/IndexEngineTest.cs
- Test/MyPeptideTest.cs
- Test/SearchEngineTests.cs
- Test/TestTopDown.cs
- Test/XLTest.cs
> indexes output folder

- EngineLayer/ProteinParsimony/ProteinGroup.cs
- Test/RobTest.cs
https://github.com/smith-chem-wisc/MetaMorpheus/issues/1677
> fix redundancy in occupancy stuff

- EngineLayer/GlobalVariables.cs
- TaskLayer/MetaMorpheusTask.cs
- TaskLayer/SearchTask/PostSearchAnalysisTask.cs
- Test/TestTopDown.cs
> proteoform file naming for top-down searches

- README.md
Link back to same page from downloads badge to not get 404 error
> Fix 404 error from downloads badge

- CMD/Program.cs
- TaskLayer/GlycoSearchTask/PostGlycoSearchAnalysisTask.cs
- Test/OutputTest.cs
in the current release, none of the glyco results files show up in the GUI
also, the file extension of them is incorrect (psm.tsv) which makes them invisible to MetaDraw without extension change.
This PR fixes those two problems
> show files in gui and rename psmtsv

- README.md
Hi all,
While installing and testing MetaMorpheus, I realized that the test filenames in the README.md and the filenames in the Box do not match.
I updated the part of the docs to fix this, so following the installation instructions and copy pasting the command works again.
Thanks for developing and maintaining this software, I highly appreciate your efforts!
Best,
Manuel
> update Usage in README with new filenames in Box

- EngineLayer/ExperimentalDesign.cs
- TaskLayer/CalibrationTask/CalibrationTask.cs
- TaskLayer/SearchTask/PostSearchAnalysisTask.cs
- Test/CalibrationTests.cs
Fixed a bug where the Calibration task did not write the Experimental Design file correctly
> Fix calibration/experimental design bug

- CMD/Program.cs
https://github.com/smith-chem-wisc/MetaMorpheus/issues/2046
> Requesting help menu shouldn't be considered an error

- EngineLayer/SpectralLibrarySearch/SpectralLibrary.cs
- GUI/MetaDraw/MetaDrawSettingsWindow.xaml.cs
- GUI/TaskWindows/GPTMDTaskWindow.xaml.cs
- GUI/TaskWindows/SearchTaskWindow.xaml.cs
- GUI/Util/GlobalGuiSettings.cs
- GuiFunctions/MetaDraw/PeptideSpectrumMatchPlot.cs
> fix culture-dependent double parsing in a few places

- GuiFunctions/MetaDraw/MetaDrawSettings.cs
- GuiFunctions/MetaDraw/MetaDrawSettingsSnapshot.cs
- Test/MetaDrawSettingsAndViewsTest.cs
Fixed a bug in loading internal ion color and background peak color from saved default settings
> Meta draw settings bug fix

- EngineLayer/ProteolyticDigestion/proteases.tsv
(with the appropriate number of tabs this time)
> Added ProAlanase to proteases.tsv

- Test/SeqCoverageTest.cs
This pull request has no changes to the code. I plan to use its build as a vehicle for testers to try downloading and installing the windows version as a pre-release. I hope to establish that this can be done with out trouble at the distal end.
> Test Beta Release

- MetaMorpheus/EngineLayer/Gptmd/GptmdEngine.cs
effort to make gptmd more thread saferish
> update to gptmd engine

- MetaMorpheus/CMD/CMD.csproj
- MetaMorpheus/EngineLayer/EngineLayer.csproj
- MetaMorpheus/GUI/GUI.csproj
- MetaMorpheus/GuiFunctions/GuiFunctions.csproj
- MetaMorpheus/TaskLayer/TaskLayer.csproj
- MetaMorpheus/Test/Test.csproj
> MzLib 1.0.545

- MetaMorpheus/CMD/CMD.csproj
- MetaMorpheus/EngineLayer/EngineLayer.csproj
- MetaMorpheus/GUI/GUI.csproj
- MetaMorpheus/GuiFunctions/GuiFunctions.csproj
- MetaMorpheus/TaskLayer/TaskLayer.csproj
- MetaMorpheus/Test/Test.csproj
Updating to the new mzLib version to stabilize GPTMD results
> mzLib update

- MetaMorpheus/MetaMorpheusSetup/Product.wxs
- MetaMorpheus/Test/SearchEngineTests.cs
Isodec dlls were not added to product.wxs on release. 
Oops
This PR adds them and all other missing references
> Hotfix: IsoDec and other Missing dlls :(

- .github/workflows/Test.yml
Runs all tests via Github actions.
> Create Testing Github Action

- MetaMorpheus/GUI/MainWindow.xaml.cs
We did not accept shortcut paths before, now we do .
> Main window file drop now handles shortcuts
