smith-chem-wisc/MetaMorpheus

EngineLayer/Analysis/AnalysisEngine.cs, EngineLayer/ClassicSearch/ClassicSearchEngine.cs, EngineLayer/Indexing/IndexingEngine.cs, EngineLayer/Proteomics/ProteinExtensions.cs, GUI/CalibrateTaskWindow.xaml, GUI/CalibrateTaskWindow.xaml.cs, GUI/GPTMDTaskWindow.xaml, GUI/GPTMDTaskWindow.xaml.cs, GUI/SearchTaskWindow.xaml, GUI/SearchTaskWindow.xaml.cs, TaskLayer/CalibrationTask/CalibrationTask.cs, TaskLayer/GPTMDTask/GPTMDTask.cs, TaskLayer/SearchTask/SearchTask.cs, Test/AnalysisEngineTest.cs, Test/CalibrationEngineTest.cs, Test/GPTMDengineTest.cs, Test/IndexEngineTest.cs, Test/LocalizationTest.cs, Test/MyPeptideTest.cs, Test/MyTaskTest.cs, Test/RobTest.cs, Test/SearchEngineTests.cs
There is one part I am not sure. In order to parse Int? Input from TextBox in GUI/SearchTaskWindow.xaml.cs, I add the following code. 
+            int temp;
+           TheTask.MinPeptideLength = int.TryParse(txtMinPeptideLength.Text, out temp) ? temp : (int?)null;
+           TheTask.MaxPeptideLength = int.TryParse(txtMaxPeptideLength.Text, out temp) ? temp : (int?)null;
What you did for Another Int input is 
+      TheTask.MaxMissedCleavages = int.Parse(missedCleavagesTextBox.Text, CultureInfo.InvariantCulture);
=> Add peptide Length textbox

EngineLayer/Indexing/IndexingEngine.cs, TaskLayer/SearchTask/SearchTask.cs, TaskLayer/XLSearchTask/XLSearchTask.cs, Test/AddCompIonsTest.cs, Test/IndexEngineTest.cs, Test/SearchEngineTests.cs
When we added the option to search for only decoys, we opened up the possibility for the indexing engine to mistake the target index for the decoy index and vise-versa. This commit adds the parameter to the params file to prevent reading the incorrect file.
=> Added SearchDecoy parameter to IndexingEngine

CMD/CMD.csproj, CMD/packages.config, EngineLayer/EngineLayer.csproj, EngineLayer/Mods/Mods.txt, EngineLayer/Mods/substitutions.txt, EngineLayer/packages.config, GUI/GUI.csproj, GUI/packages.config, TaskLayer/TaskLayer.csproj, TaskLayer/packages.config, Test/Test.csproj, Test/packages.config
* Update Mods.txt
* Update Mods.txt
* Update Mods.txt
=> Update mzLib to fix crash with old calibrated files, split substitutions by nucleotide difference, add mods

GUI/MainWindow.xaml.cs
- Fix crash when bad toml dragged in to GUI (displays warning)
- The same crash occurred when a ppm suggestion toml from the calibration task was dragged in; this does not cause a crash and displays no warning
=> fix toml crashes

EngineLayer/ClassicSearch/ClassicSearchEngine.cs, EngineLayer/GlobalVariables.cs, EngineLayer/HistogramAnalysis/Bin.cs, EngineLayer/Neo/PsmTsvLine.cs, EngineLayer/ProteinParsimony/ProteinGroup.cs, EngineLayer/Psm.cs, GUI/MainWindow.xaml, GUI/MainWindow.xaml.cs, GUI/SearchTaskWindow.xaml, GUI/SearchTaskWindow.xaml.cs, TaskLayer/CalibrationTask/CalibrationTask.cs, TaskLayer/SearchTask/SearchParameters.cs, TaskLayer/SearchTask/SearchTask.cs, Test/AddCompIonsTest.cs, Test/MyTaskTest.cs, Test/RobTest.cs, Test/SearchEngineTests.cs
- Change ambiguity delimiter from " or " to "|"
- Quantification enabled by default
- Fixed crash when no PSMs are detected and quantification is enabled
- Arrange proteins within a protein group by alphabetical order of accession number (helps keeps results consistant across searches)
- Temporarily disable Neo button
- Removed unimplemented q-value output filtering from the GUI
- Fixed crash when no proteins are in the protein list (loading a blank fasta might still be buggy)
- Fixed an error in calibration that suggested bad ppm tolerances in the written .toml
- Fix crash when 0 proteins are in the protein list to search
- Fix crash when spectra files from different folders are dragged in to GUI
- Fixed bug where if a output folder was defined in the GUI, adding a new spectra file …
=> misc changes

GUI/SearchTaskWindow.xaml, GUI/SearchTaskWindow.xaml.cs, TaskLayer/SearchTask/MyFileManager.cs
- disable ms/ms peak filtering because of major bug in mzlib (#996)
=> disable ms/ms peak filtering because of major bug in mzlib (#996)

EngineLayer/CommonParameters.cs, GUI/CalibrateTaskWindow.xaml.cs, GUI/FileSpecificParametersWindow.xaml.cs, GUI/GPTMDTaskWindow.xaml.cs, GUI/NeoSearchTaskWindow.xaml.cs, GUI/SearchTaskWindow.xaml.cs, GUI/XLSearchTaskWindow.xaml.cs, TaskLayer/CalibrationTask/CalibrationTask.cs
This one makes all fields have private setters where possible and explicit public setters where necessary. This will at least reduce the work in maintaining the Clone() method, which will automatically repopulate the properties of the clone. This also cleans up the GUI code for TaskDescriptor a bit.
=> Smaller refactor to common parameters

EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs, EngineLayer/ProteinParsimony/ProteinParsimonyEngine.cs, EngineLayer/ProteinScoringAndFdr/ProteinScoringAndFdrEngine.cs, TaskLayer/CalibrationTask/CalibrationTask.cs, TaskLayer/GPTMDTask/GPTMDTask.cs, TaskLayer/SearchTask/PostSearchAnalysisTask.cs, TaskLayer/SearchTask/SearchTask.cs, TaskLayer/XLSearchTask/XLSearchTask.cs
- fix "cumulative target" skipping numbers
- parsimony doesn't use ambiguous PSMs
=> fix "cumulative target" skipping numbers

GUI/CalibrateTaskWindow.xaml.cs, GUI/GPTMDTaskWindow.xaml.cs, GUI/SearchTaskWindow.xaml.cs, GUI/XLSearchTaskWindow.xaml.cs
The TextChangedTimerHandler events were not being removed from the static timer, which seemed to cause this issue. Removing them on window close solves it.
=> fix issue #1713

GUI/MetaDraw/PlotModelStat.cs
- Change predicted rt to predicted hydrophobicity in meta draw plot (complete)
- in ppm histogram have x axis have 2 decimal places ( in progress)
=> Small MetaDraw Fixes 

TaskLayer/SearchTask/PostSearchAnalysisTask.cs
A user wants the mzid input to be filter to 1% for downstream processing. Currently, when the q-value < 0.01 cuttoff is used, it is applied to everything except mzid and pepxml. I changed the output for those two to match. Now they are filtered when the checkbox is checked.
=> changed mzid and pepxml output to be filtered by q-value cutoff

EngineLayer/FdrAnalysis/PEPValueAnalysisGeneric.cs, Test/XLTest.cs
Now that PEP is stabilized, I'm going to look at some small adjustments. In this first commit, I ran three separate large searches to compare test metrics of PEP between keeping high q-value Targets in the false training set or using only decoys. I found in all three cases that using only decoys for the false set produced superior recall results. Therefore, I am eliminating the high q-value targets from training. Anyway, there are a bazillion decoys to choose from.
=> Remove high q-value Targets from PEP training

CMD/CommandLineSettings.cs
**pull request type:**
bugfix
**problem:**
the command-line version of MM generates default .toml files for each task with the `-g` flag. the glyco search was not included in this, making it dependent on the GUI version to generate its .toml files.
**solution:**
added the glyco search task to the list of .toml files generated by the `-g` flag.
**repercussions of solution:**
none
=> generate glyco default toml via CMD

EngineLayer/GlobalVariables.cs, GUI/MainWindow.xaml.cs
#1872 
**problem:**
when a program is not associated with .toml, going to settings -> close MM and open settings, MM is closed but the .toml is not opened. this gives the appearance of a crash, and does not let the user edit the settings as expected. windows does not prompt for a program to open .toml with in some cases, though this appears to be variable.
**solution:**
notepad is used as the default .toml editor in specific cases (editing settings.toml or GUIsettings.toml).
**created problems:**
- user may not want to use notepad as .toml editor to edit settings.toml or GUIsettings.toml.
- other .toml files are not affected, possibly creating confusion; .tomls are edited by notepad in some places but do not open at all in other places which can give the appearance of a bug. we could use …
=> issue 1872

CMD/CMD.csproj, EngineLayer/EngineLayer.csproj, GUI/GUI.csproj, TaskLayer/TaskLayer.csproj, Test/Test.csproj
i added the ability to download a database from uniprot to this version of mzlib. i plan to add that functionality to metamorpheus. This pull request is to update metamorpheus to the newest mzlib release 475.
I tested calibration,gptmd and search with a raw file from the vignette. Seems to work just fine.
=> updated metamorpheus to mzlib nuget package release 475

EngineLayer/PsmTsv/PsmFromTsv.cs, GUI/MainWindow.xaml, GUI/MainWindow.xaml.cs, GUI/MetaDraw/MetaDraw.xaml.cs, Test/MetaDrawTest.cs, Test/SearchEngineTests.cs
#1958 
- Can select multiple DB/spectra files and delete them
- Delete key on the keyboard will delete tasks
- Plus or minus keys will move tasks up or down
- Double-clicking a file or task will open it
- If all spectra files are deleted, the output file path is cleared
- Can right click -> Delete All for spectra, protein DBs, tasks
- Can right click -> Move task up or Move task down
- Clicking the "Select" button in MetaDraw (to add a spectra file or results file) will correctly display .mgf and .tsv as options
- Fixed a crash loading XL Task results in MetaDraw
- Increased the font size of the tasks in the Run tab from 11 to 13
- Added grid splitters to the Run tab so that the DB/spectra/tasks areas can be resized
=> bugfixes for the GUI

EngineLayer/GlobalVariables.cs, EngineLayer/PsmTsv/PsmFromTsv.cs, GUI/MetaDraw/MetaDraw.xaml.cs, Test/GlobalVariablesTest.cs
custom file extension getter that is more reliable than the microsoft one.
- can handle compressed files like .fasta.gz
- ignores periods in file names
- this change allows MetaDraw to load data from spectra files with periods in the name. related to #1974
=> custom file extension getter

CMD/CommandLineSettings.cs, EngineLayer/GlobalVariables.cs, Test/GlobalVariablesTest.cs
can specify a directory of spectra files. fixes #1901 .
unfortunately, no unit test for the new CMD option as this seems to not play well w/ appveyor. but I did manually test it.
=> ability to add spectra file directory in CMD

GUI/ExperimentalDesignWindow.xaml, GUI/ExperimentalDesignWindow.xaml.cs, GUI/ForDisplayingInDataGrids/ExperimentalDesignForDataGrid.cs
- Add ability to copy+paste tab- or comma-delimited cells into the Experimental Design window, e.g. from Excel (currently only w/ the ctrl+V keyboard shortcut)
- Fix an issue in the experimental design GUI where the buttons at the bottom of the window obscured data cells
=> small experimental design GUI changes

Dockerfile
this PR installs bash and procps in the Linux docker image. bash is required to run metamorpheus in a nextflow pipeline, and procps lets nextflow monitor computational resources used by the image.
=> [WIP] install bash and procps in docker version for nextflow

GUI/TaskWindows/SearchTaskWindow.xaml.cs
This is a GUI specific update. Selecting "non-specific" as the protease in the search task triggers a prompt suggesting default settings that we have found to be a useful start point for a non-specific search. This update changes one of the defaults, the mode of search from "classic" to "non-specific". This should give equivalent results but the search should be faster. The search mode can be found in "Advanced Options/Some Search Parameters/Search Mode".
This update solves the issue raised in #1846 
https://github.com/smith-chem-wisc/MetaMorpheus/issues/1846
=> GUI Auto Settings Bug Fix

CMD/CMD.csproj, EngineLayer/EngineLayer.csproj, GUI/GUI.csproj, GuiFunctions/GuiFunctions.csproj, TaskLayer/TaskLayer.csproj, Test/Test.csproj
This nuget package update fixes a problem where certain mgf containing tab-separated data are not readible. See issue raised in mzlib https://github.com/smith-chem-wisc/mzLib/issues/610
=> update nuget 518

EngineLayer/EngineLayer.csproj, GUI/GUI.csproj
Update EngineLayer and GUI nuget package Newtonsoft_Json to version 13.0.1, which is the current stable version.
https://github.com/smith-chem-wisc/MetaMorpheus/security/dependabot/1
Newtonsoft.Json prior to version 13.0.1 is vulnerable to Insecure Defaults due to improper handling of StackOverFlow exception (SOE) whenever nested expressions are being processed. Exploiting this vulnerability results in Denial Of Service (DoS), and it is exploitable when an attacker sends 5 requests that cause SOE in time frame of 5 minutes. This vulnerability affects Internet Information Services (IIS) Applications.
=> update newtonsoftJson because of security concerns

GuiFunctions/MetaDraw/MetaDrawLogic.cs, GuiFunctions/MetaDraw/MetaDrawSettings.cs, GuiFunctions/ViewModels/ModForTreeViewModel.cs, GuiFunctions/ViewModels/SettingsViewModel.cs, Test/MetaDrawSettingsAndViewsTest.cs
Fixed a bug where meta draw would crash if there was not a default param directory. Added default colors to some mods per Austin's suggestion in my previous pull request
These defaults in windows are added to \user\user\appdata\local\metamorpheus\defaultparameters
can be reset by deleting those files
=> Meta draw default settings bug fix and default mod colors

EngineLayer/PsmTsv/PsmFromTsv.cs, GUI/App.xaml, GUI/MetaDraw/MetaDraw.xaml, GUI/MetaDraw/MetaDraw.xaml.cs, GUI/MetaDraw/MetaDrawSettingsWindow.xaml, GUI/MetaDraw/MetaDrawSettingsWindow.xaml.cs, GuiFunctions/GuiFunctions.csproj, GuiFunctions/MetaDraw/DrawnSequence.cs, GuiFunctions/MetaDraw/MetaDrawLogic.cs, GuiFunctions/MetaDraw/MetaDrawSettings.cs, GuiFunctions/MetaDraw/MetaDrawSettingsSnapshot.cs, GuiFunctions/MetaDraw/PeptideSpectrumMatchPlot.cs, GuiFunctions/ViewModels/IonForTreeViewModel.cs, GuiFunctions/ViewModels/IonTypeForTreeViewModel.cs, GuiFunctions/ViewModels/PtmLegendViewModel.cs, GuiFunctions/ViewModels/SettingsViewModel.cs, Test/MetaDrawSettingsAndViewsTest.cs, Test/MetaDrawTest.cs
Additional Features:
Color options for background peaks and internal ions
MetaDraw specific reset defaults button
Spectrum description elements PEP and PEP-Q only show three decimals
Sort list of psms by protein name, species of origin, q-value, pep, and MetaMorpheus Score
Filter psms by ambiguity level
Changes:
Data visualization charts now export to same folder as the rest of the images
Spectrum description 'spectral angle' field now off by default
Bug Fixes:
Resizing after psm or spectra files were reset caused a crash
Sequence annotation and stationary sequence ptm annotation positioning corrected
Export child scan as pdf now includes ptm color legend
Export sequence coverage no longer cuts off the sequence text
Sequence coverage now stays the correct size when the window is resolved …
=> MetaDrawPolishing

EngineLayer/PsmTsv/PsmFromTsv.cs, Test/SearchTaskTest.cs
Fixed bug in PsmTsvReader where internal ions intensity value was assigned their charge state
=> PsmTsvReader Bug Fix

GUI/Views/FileSpecificParametersWindow.xaml
Adding the option for file specific dissociation type to file specific settings window caused the window to be undersized on some monitors. This PR adjusts the default window size and adds the ability to scroll the buttons if the user makes the window vertical size smaller than the height needed to accommodate all the buttons. Also, set button is pinned to the bottom and is always visible regardless of overall window height. Thanks Nic.
=> adjusted file specific parameters window

Test/Test.csproj, global.json
Appveyor recently started including .NET 7 with the Visual Studio 2022 image. This broke coverlet. Added a global.json to set the correct version of .NET
=> Added global.json

CMD/CMD.csproj, EngineLayer/Calibration/DataPointAquisitionResults.cs, EngineLayer/EngineLayer.csproj, GUI/GUI.csproj, TaskLayer/TaskLayer.csproj
nett is now version 0.15.0
Mathnet.Numerics is now version 5.0.0
One class, DataPointAcquisitionResults, had issues with the new version of Mathnet.Numerics and was changed to maintain the same behavior. The previous version of the code called the method MeanStandardDeviation whose definition in the Mathnet.Numerics code is below
The code that has been changed, simply implements this in our class.
=> Updated Nuget packages that were updated in MzLib

EngineLayer/ClassicSearch/MiniClassicSearchEngine.cs
Previously, theoretical fragments were being generated multiple times instead of stored in the targetFragmentsForEachDissociationType Dictionary. 
Now, fragments are stored in the dictionary.
=> Fixed issue in MiniClassicSearchEngine

MetaMorpheus/CMD/CMD.csproj, MetaMorpheus/EngineLayer/EngineLayer.csproj, MetaMorpheus/GUI/GUI.csproj, MetaMorpheus/GuiFunctions/GuiFunctions.csproj, MetaMorpheus/TaskLayer/TaskLayer.csproj, MetaMorpheus/Test/Test.csproj
Update to the latest version of mzLib. 
mzLib 538 employs a slightly different method for calculating protein intensities which results in fewer missing values.
=> Updated mzLib to 1.0.538

MetaMorpheus/GUI/MetaDraw/MetaDraw.xaml.cs, MetaMorpheus/GuiFunctions/MetaDraw/DrawnSequence.cs
MetaDraw was crashing when you attempted to view XL results. I added a couple of null checks that resolved the issue (#2289.)
MetaDraw was and continues to crash when attempting to read in the Deadends.tsv output from XLSearchTask. This is due to dead ends being recorded as an unrecognized modification. Should maybe be addressed at some point, but it's outside the scope of this PR.
=> Added null checks to enable display of XL results

MetaMorpheus/GUI/MainWindow.xaml.cs
This should make the task windows (and MetaDraw) pop up in front of the main window
=> Changed the main window to own the subsequent windows

MetaMorpheus/CMD/CMD.csproj, MetaMorpheus/EngineLayer/EngineLayer.csproj, MetaMorpheus/GUI/GUI.csproj, MetaMorpheus/GuiFunctions/GuiFunctions.csproj, MetaMorpheus/TaskLayer/TaskLayer.csproj, MetaMorpheus/Test/GuiFunctionsTest.cs, MetaMorpheus/Test/Test.csproj
Updated to mzlib with reduced complexity scan accessing, this will reduce time to run calibration. 
Updated one unit test to no longer run in parallel as collisions were occurring with file accessing. 
Updated the same unit test to reflect a change in the total number of proteins present in the database as changed by uniprot. 
This version of mzlib will also correctly load fasts.gz files
=> Updated to MzLib 1.0.541 and updated one unit test

MetaMorpheus/GUI/MainWindow.xaml, MetaMorpheus/MetaMorpheusSetup/Product.wxs
SpectralAveraging.dll was not being packaged properly with the Wix Installer. This PR adds the lines to the wix install script to package the new dll within mzlib correctly. 
Future work should dig into why this is not happening automatically.
=> Added SpectralAveraging.dll to project.wxs

MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs, MetaMorpheus/EngineLayer/PsmTsv/PsmTsvWriter.cs, MetaMorpheus/Test/MultiProteaseParsimonyTest.cs, MetaMorpheus/Test/PeptideSpectralMatchTest.cs, MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs, MetaMorpheus/Test/PsvTsvTest.cs, MetaMorpheus/Test/SearchTaskTest.cs, MetaMorpheus/Test/TestPsm.cs
We have never used the correct calculation for q-value, which is (decoy count + 1)/(target count). This is because, the highest scoring PSM would have q-value = 0.5. Bill Noble alerted me to an alternate strategy for computing q-value that would eliminate this problem and allow us to use the correct formula. This is accomplished by computing q-value from lowest scoring PSM to highest scoring PSM subject to the following rule. Whenever the current q-value is greater than the previous q-value, we keep the previous q-value. Now, the highest scoring PSM will have a q-value equal to the q-value of the highest scoring decoy PSM. It will never be zero. c est la vie.
overall we expect to see a higher yield of both peptides and PSMs with q-value < 0.01.
An unfortunate by product of this update is …
=> Invert q-value

MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml
Quick little PR to add some tool tip boxes to the cross link search task view. I only added a handful of the Xlink specific ones, pulled from the Wiki with some light editing.
=> Added some tooltips for the cross link search task view.

MetaMorpheus/EngineLayer/PrecursorSearchModes/DotMassDiffAcceptor.cs, MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
Resolves https://github.com/smith-chem-wisc/MetaMorpheus/issues/1827
=> Polishing prose

MetaMorpheus/CMD/CMD.csproj, MetaMorpheus/EngineLayer/EngineLayer.csproj, MetaMorpheus/GUI/GUI.csproj, MetaMorpheus/GuiFunctions/GuiFunctions.csproj, MetaMorpheus/TaskLayer/TaskLayer.csproj, MetaMorpheus/Test/Test.csproj
new release of mzlib
https://github.com/smith-chem-wisc/mzLib/releases/tag/1.0.551
DecoyScrambler now accounts for modifications by @Alexander-Sol in https://github.com/smith-chem-wisc/mzLib/pull/795
Updated SpectraFileInfo, changed fields to properties by @Alexander-Sol in https://github.com/smith-chem-wisc/mzLib/pull/794
=> update mzlib nuget package to 551

MetaMorpheus/TaskLayer/FilteredPsms.cs
Previously, when filtering, we iterated through the list of PSMs 6 times. Now, we only iterate through once in a single LINQ statement. This should give a modest performance increase.
=> Updated FilteredPsms to only iterate through PSMs once

MetaMorpheus/TaskLayer/CalibrationTask/CalibrationTask.cs
The calibration task presently writes calibration tolerances out to 4 decimal places. There is some run to run variability in this number which may or may not have downstream consequences. This PR rounds both precursor and product tolerances to 1 decimal place. I have not observed any variation in calibration tolerance that occurs at this high level.
=> round calibration tolerance to one decimal place

MetaMorpheus/EngineLayer/NonSpecificEnzymeSearch/NonSpecificEnzymeSearchEngine.cs, MetaMorpheus/Test/SearchEngineTests.cs, MetaMorpheus/Test/Test.csproj, MetaMorpheus/Test/TestData/NonSpecificSearchToml.toml, MetaMorpheus/Test/TestData/bosTaurusEnamPruned.xml
non-specific search engine has a bug where a second modification is attempted to be added to a peptide with set mods where there is an existing modification at that position. This PR adds a check that prevents addition of the second mod.
=> nonspecific search engine bug fix and unit test

MetaMorpheus/GuiFunctions/MetaDraw/DrawnSequence.cs, MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawSettings.cs, MetaMorpheus/GuiFunctions/ViewModels/CoverageTypeForTreeViewModel.cs, MetaMorpheus/GuiFunctions/ViewModels/IonForTreeViewModel.cs, MetaMorpheus/GuiFunctions/ViewModels/ModForTreeViewModel.cs, MetaMorpheus/Test/MetaDraw/MetaDrawSettingsAndViewsTest.cs
Task window launch was slowed down because the View model behind each modification checkbox was loading the MetaDraw color for it from a slow reflection method: OxyPlot.GetColorName(). 
This pull request improves loading time by 
1. Deferring instantiation of color related data until it is first called. 
2. Using a cached value in MetaDrawSettings instead of calling the OxyPlot slow reflection method. 
Improvements to color parsing and handling:
* [`MetaMorpheus/GuiFunctions/MetaDraw/DrawnSequence.cs`](diffhunk://#diff-6052a29d4ed153419466b3cbc1d54b74a09485576876a69b01c91e281dab7d1cL384-R403): Simplified the `ParseColorBrushFromOxyColor`, `ParseColorBrushFromName`, and `ParseOxyColorFromName` methods by removing unnecessary string manipulations and adding fallback color handling.
* …
=> Speed up task window launch

MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml, MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/GlycoSearchTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml.cs
Added the option to set custom deconvolution parameters in calibration. 
Added MetaMorpheusTask.DetermineAnalyteType(TheTask.CommonParameters) 
at the beginning of the UpdateFieldsFromTask method in task windows. This ensures analyte type is determined and set
before updating fields from the task.
=> Added Decon Parameters to Calibration Window

MetaMorpheus/EngineLayer/FdrAnalysis/PEPAnalysisEngine.cs, MetaMorpheus/Test/PostSearchAnalysisTaskTests.cs, MetaMorpheus/Test/TestData/Task1-SearchTaskconfig.toml
In the PEP analysis engine, multiple threads need to read in the stored model. Currently, no lock is activated during reading, which can result in multiple threads reading the model simultaneously, resulting in a crash.
I'm not sure how to write unit tests for lock objects, so I was hoping we could let this one get through with low patch coverage
=> Model lock

MetaMorpheus/EngineLayer/SpectralMatch.cs, MetaMorpheus/GUI/TaskWindows/CalibrateTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/GPTMDTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/GlycoSearchTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml, MetaMorpheus/GUI/TaskWindows/SearchTaskWindow.xaml.cs, MetaMorpheus/GUI/TaskWindows/XLSearchTaskWindow.xaml.cs, MetaMorpheus/GUI/Util/GlobalGuiSettings.cs, MetaMorpheus/TaskLayer/FilteredPsms.cs, MetaMorpheus/TaskLayer/SearchTask/PostSearchAnalysisTask.cs, MetaMorpheus/TaskLayer/SearchTask/SearchParameters.cs
The current version of mzLib has had some significant changes made to MBR in FlashLFQ.
This update supports those changes.
- Added property to SearchParameters - MbrFdrThreshold. This controls the FDR of MBR identifications
- Added text box in Search Task to allow users to set this parameter
- Call to the FlashLFQ engine in PostSearchAnalysisTask receives additional argument - PeptidesToQuantify
- This ensures that only peptides with a **peptide-level Q-value** <0.01 are written to the output and used to calculate protein intensities 
- Identifications passed in to FlashLFQ now have additional information: Score, Q-value, and bool isDecoy.
=> Made updates pertaining to PIP-ECHO

MetaMorpheus/EngineLayer/ClassicSearch/ClassicSearchEngine.cs, MetaMorpheus/EngineLayer/ClassicSearch/MiniClassicSearchEngine.cs, MetaMorpheus/EngineLayer/ScanWithIndexAndNotchInfo.cs, MetaMorpheus/EngineLayer/Util/ScanWithIndexAndNotchInfo.cs, MetaMorpheus/Test/XLTest.cs
`ScanWithIndexAndNotchInfo` is a small class that is created, used, and destroyed a bunch of times, very very quickly. There is no reason we need to carry around the `Ms2ScanWithSpecificMass` every time we create one of these objects when the `ScanWithIndexAndNotchInfo` contains the index of the scan. 
The scan has been removed from the object. 
This 1-to-1 mapping of index to scan breaks down in `MiniClassicSearchEngine`, so that class will maintain original functionality. 
Adjusted the Ms2Ms2 test to not break 50% of the time
=> Scan with index and notch update

MetaMorpheus/CMD/CMD.csproj, MetaMorpheus/EngineLayer/EngineLayer.csproj, MetaMorpheus/EngineLayer/Silac/SilacConversions.cs, MetaMorpheus/GUI/GUI.csproj, MetaMorpheus/GuiFunctions/GuiFunctions.csproj, MetaMorpheus/TaskLayer/TaskLayer.csproj, MetaMorpheus/Test/Test.csproj
Refactored SilacConversions code from using ZeroBasedMS1ScanIndex to ZeroBasedScanIndex, which is correct in the newly added IIndexedMzPeak.
=> Refactoring to use IIndexedMzPeak

MetaMorpheus/EngineLayer/Gptmd/GptmdEngine.cs, MetaMorpheus/EngineLayer/SpectralMatch.cs, MetaMorpheus/TaskLayer/GPTMDTask/GPTMDTask.cs, MetaMorpheus/Test/GPTMDengineTest.cs
My recent refactor to the GPTMD engine decreases the number of modified peptides identified in bottom-up data. This PR reverts those changes. 
- SpectralMatch: Spectral match now has an Ms2Scan property that is only used within the GPTMD task
- GPTMDTask: FDR analysis is now done on all PSMs from all files at once, instead of file-by-file
- GPTMDEngine: The engine now gets the MsDataScan directly from the Ms2Scan property of each PSM
=> Changed GPTMD back to the way it was

MetaMorpheus/GUI/MetaDraw/MetaDraw.xaml.cs, MetaMorpheus/GuiFunctions/MetaDraw/DrawnSequence.cs, MetaMorpheus/GuiFunctions/MetaDraw/FragmentResearching/FragmentationReanalysisViewModel.cs, MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawLogic.cs, MetaMorpheus/GuiFunctions/MetaDraw/MetaDrawSettings.cs, MetaMorpheus/GuiFunctions/MetaDraw/PlotModelStat.cs, MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/ChimeraSpectrumMatchPlot.cs, MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/PeptideSpectrumMatchPlot.cs, MetaMorpheus/GuiFunctions/MetaDraw/SpectrumMatch/SpectrumMatchPlot.cs, MetaMorpheus/GuiFunctions/MzLibExtensions.cs, MetaMorpheus/GuiFunctions/ViewModels/Legends/ChimeraLegendViewModel.cs, MetaMorpheus/GuiFunctions/ViewModels/Legends/PtmLegendViewModel.cs, MetaMorpheus/Test/MetaDraw/MetaDrawSettingsAndViewsTest.cs, MetaMorpheus/Test/MetaDraw/MetaDrawTest.cs, MetaMorpheus/Test/MetaDraw/SpectrumMatchPlotTests.cs, MetaMorpheus/Test/PsvTsvTest.cs, MetaMorpheus/Test/SearchEngineTests.cs, MetaMorpheus/Test/SpectralRecoveryTest.cs
Removed protein specific fields from MetaDraw and generalized for oligos as well.
=> Generalize MetaDraw to use SpectrumMatchFromTsv

MetaMorpheus/EngineLayer/ProteinParsimony/ProteinParsimonyEngine.cs
GlycoSpectralMatch inherits from SpectralMatch and not PeptideSpectralMatch. This caused a crash during protein parsimony and is fixed in this PR.
=> Fix Glyco Crash on ProteinParsimony

MetaMorpheus/CMD/CMD.csproj, MetaMorpheus/EngineLayer/EngineLayer.csproj, MetaMorpheus/EngineLayer/MetaMorpheusException.cs, MetaMorpheus/GUI/GUI.csproj, MetaMorpheus/GuiFunctions/GuiFunctions.csproj, MetaMorpheus/TaskLayer/MetaMorpheusTask.cs, MetaMorpheus/TaskLayer/TaskLayer.csproj, MetaMorpheus/Test/Test.csproj, MetaMorpheus/Test/TestToml.cs
Updated mzlib and added new toml handling for average residue models. Not the best way to handle it as you need to add a new line to the toml parser for each now model created, but it is good enough for now. A more robust approach would require a factory in MzLib.
=> Update mz lib
